### ISSUE TITLE
Namespace mistake ?

### ISSUE THREAD

**Issue by Vitexus** [WyriHaximus/php-file-descriptors#60]
I got

```
PHP Fatal error:  Uncaught Error: Call to undefined function Safe\\scandir() in /var/lib/composer/discomp2abraflexi/wyrihaximus/file-descriptors/src/ScanDir.php:22
Stack trace:
#0 /var/lib/composer/discomp2abraflexi/wyrihaximus/file-descriptors/src/ProcSelfFd.php(20): WyriHaximus\\FileDescriptors\\ScanDir::scan()
#1 /usr/share/discomp2abraflexi/Discomp/Importer.php(303): WyriHaximus\\FileDescriptors\\ProcSelfFd->list()
#2 /usr/share/discomp2abraflexi/discomp2abraflexi.php(34): SpojeNet\\Discomp\\Importer->freshItems()
#3 {main}
  thrown in /var/lib/composer/discomp2abraflexi/wyrihaximus/file-descriptors/src/ScanDir.php on line 22
```

I think, the problem is 

```php
use function Safe\scandir;
```

I suggest simple fix https://github.com/WyriHaximus/php-file-descriptors/pull/59

**Comment by WyriHaximus** [comment]
Hey thanks for reporting, it's missing the https://github.com/thecodingmachine/safe package in composer.json. Which will throw on any error instead of returning false or another way of not loudly failing. Will have a look at your PR later today or tomorrow.
